### ISSUE TITLE
Allow using Github App Token

### ISSUE THREAD

**Issue by Shahaed** [CasperWA/push-protected#144]
A token from a Github App can have the same permissions as an admin PAT and is probably more appropriate to use than a PAT. (Github App tokens can be gotten this way: https://github.com/tibdex/github-app-token).

This action currently doesn't support tokens from a Github App (even with the correct permissions) because this line: https://github.com/CasperWA/push-protected/blob/035cda7fdfb10a7d41e45646da8340d0223ac094/push_action/utils.py#L292

checks for the `admin` property in the `permission` object in the response which a Github App can't have be true. 

I think the easiest way to do this would be by removing the admin check and if someone is using a token with insufficient permissions, fail at that specific api.

**Comment by CasperWA** [comment]
@Shahaed do you have a possibility to test out the currently open PR? It can be tested by changing the version of the action to instead point to `cwa/close-144-allow-app-tokens`:

```yaml
uses: CasperWA/push-protected@cwa/close-144-allow-app-tokens
with:
  token: ...
```
