### ISSUE TITLE
Support GH enterprise

### ISSUE THREAD

**Issue by zentale** [CasperWA/push-protected#201]
I see github.com is hardcoded in these lines.
https://github.com/CasperWA/push-protected/blob/f28401e8720f752c9dc4f1e0bd8e0641434ab1ee/entrypoint.sh#L105-L107
It would be awesome to have a parameter for the github instance.

**Comment by zentale** [comment]
It wouldnt need a parameter, since there is an env variable available as default.

https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
`GITHUB_SERVER_URL`

**Comment by CasperWA** [comment]
@zentale, please use the upcoming v2.15.0 to check whether #205 truly fixed this issue.
