### ISSUE TITLE
Feature request: commit signing, or disable also that requirement

### ISSUE THREAD

**Issue by punasusi** [CasperWA/push-protected#230]
I've given PAT for the single repo which settings rights. It successfully commits to a protected branch, as expected.
However, when I enable enforce commit signing, it fails with "Commits must have verified signatures". 

Either a way to give a signing key, or use the admin rights to also remove the commit signing rule as well as the review protection.

**Comment by MattiSG** [comment]
As I understand it, this action does not create any commit. It only pushes. If you create a commit in your previous steps, these should be signed. See for example [this post](https://github.com/Nautilus-Cyberneering/pygithub/blob/main/docs/how_to_sign_automatic_commits_in_github_actions.md#solution-02-using-your-own-pgp-key-as-a-secret) on how to do that.

**Comment by CasperWA** [comment]
As @MattiSG stated, this indeed correct. Any changes you are pushing with this action are done outside the scope of this action, i.e., in prior workflow job steps.
See also [this section](https://github.com/CasperWA/push-protected?tab=readme-ov-file#usage) of the README (especially the last part) and note that this action actually removes any uncommitted changes prior to pushing (see [this line](https://github.com/CasperWA/push-protected/blob/main/entrypoint.sh#L200)).
