### ISSUE TITLE
unprotect_reviews not doing its job

### ISSUE THREAD

**Issue by juris** [CasperWA/push-protected#54]
I have a basic workflow and a protected branch with reviewers protection rule.
Here is a workflow
```
      -
        name: Run npm update
        run: |
          npm update
          git add package.json package-lock.json
          git commit -m "automatic npm update"
      -
        name: Push to Protected Branch
        uses: CasperWA/push-protected@master
        with:
          branch: development
          token: ${{ secrets.PAT }}
          unprotect_reviews: 'true'
```

and here is an error
```
Getting latest commit of REDACTED/REDACTED@development ... DONE!

Creating temporary branch 'push-action/1407251099/5806-29781-17221' ...
Switched to a new branch 'push-action/1407251099/5806-29781-17221'
Creating temporary branch 'push-action/1407251099/5806-29781-17221' ... DONE!

Pushing 'push-action/1407251099/5806-29781-17221' -> 'origin/development' ...
Switched to branch 'development'
Your branch is ahead of 'origin/development' by 1 commit.
  (use "git push" to publish your local commits)
HEAD is now at 5337b7b8f automatic npm update
remote: error: GH006: Protected branch update failed for refs/heads/development.        
remote: error: At least 1 approving review is required by reviewers with write access.        
To https://github.com/REDACTED/REDACTED.git
 ! [remote rejected]     development -> development (protected branch hook declined)
error: failed to push some refs to 'https://github.com/REDACTED/REDACTED.git'
```

**Comment by CasperWA** [comment]
Huh, interesting. Did this used to work for this workflow? Or is this the first time you run this workflow and then got this error?

**Comment by juris** [comment]
I've tried `CasperWA/push-protected@v2` first, with no luck, then switched to `@master` but it did not help.

**Comment by CasperWA** [comment]
> I've tried `CasperWA/push-protected@v2` first, with no luck, then switched to `@master` but it did not help.

Those should be the same in functionality.
I more meant the workflow you are referencing. Is this an "old" workflow that used to work with this action or is it a new workflow you've set up?
Do you have a link to the workflow run (if you want to share it)?

**Comment by juris** [comment]
I think I found the issue. Turns out, the user has to have admin access to the repo. Otherwise he can not update reviewers setting.

**Comment by CasperWA** [comment]
I will update the README of this action then to include this - cheers for finding the solution yourself.

**Comment by juris** [comment]
Thank you for such rapid responses!
