### ISSUE TITLE
Not clear which scope should I use to enable `unprotect_reviews` option

### ISSUE THREAD

**Issue by dianjuar** [CasperWA/push-protected#60]
The documentation says that to be able to use `unprotect_reviews` I need to, and I quote _"One needs administrative access to the repository to be able to use this feature"_. 

It doesn't say which exact scope I need to enable from the [scope list](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes). The list is very long (and sometimes confusing) and would be a lot easier if you point out which is the scope that I need to enable.

**Comment by CasperWA** [comment]
Yeah, I know. But it seems to me the different relations one can have within a repository can differ quite a lot as well. One can be part of an organization that owns the repository. One can be part of a team within an organization that owns it. One can own a repository as a single user, and in all of these cases there's both public/private considerations. And even then, I'm pretty sure I haven't covered all the different ways.

In short - I don't even have the complete overview of matching scopes for this, only the knowledge that this feature does not work for you, if you do not have administrative rights to the repository, i.e., if you cannot do this through the standard GUI on GitHub already. And perhaps that's the answer? That the scope doesn't change compared to the ones already written, as long as the PAT represents a user that has administrative rights to the repository (being an "admin")?

I would welcome an update to the documentation with a full scope list versus use case or detailed explanation of this, however :) So don't hesitate to contribute/open a PR if you have suggestions.

**Comment by CasperWA** [comment]
This has been updated through #95.
